### ISSUE TITLE
[Request] Customize Hotkeys

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/codestream#105]
I have a problem with the keystroke `ALT-Enter` for sending comments etc. I use `awesome-wm` on Arch Linux and therefore can not use it in my IDEs.
There should be a way to rebind those keys.

**Comment by Nikita6000** [comment]
Same request, though for a different reason - when typing i use extensively "shft+ctrl+arrows" to select entire words instead of single characters (for example to delete and redo something i just wrote). But while typing comments in CodeStream (in JetBrains Rider) this resizes CodeStream pannel, which honestly drives me nuts, cause it's a muscle memory which i can't stop right away

**Comment by marcelofarias** [comment]
@Nikita6000 Could you confirm what IDE version are you using?

Also, since this shortcut is associated with resizing of Tool Windows in general, you can customize it in Preferences -> Keymap (Main Menu -> Window -> Active Tool Window -> Resize -> Stretch to Left/Right).

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Prevent resizing of CodeStream panel with Ctrl + Shift + Arrow](https://trello.com/c/ptwqULh4/2936-prevent-resizing-of-codestream-panel-with-ctrl-shift-arrow)
