### ISSUE TITLE
Jira ticket sometimes doesnt match PR branch number

### ISSUE THREAD

**Issue by Frosty21** [TeamCodeStream/codestream#1050]
- IDE Version: VS Code latest version
- OS Version: Mac OS latest version

Steps to Reproduce:
When going from one PR related to a jira ticket that's still waiting for PR Approval to merge to the next branch to create a PR the this relates to Jira tickets is from the previous one (something funky is happening the the cache i suspect)
![Screen Shot 2022-07-13 at 10 05 23 AM](https://user-images.githubusercontent.com/5212703/178781332-80cd4ef2-f898-4c32-a140-1e90fb2512b1.png)

Logs sent to @planteater via email

**Comment by planteater** [comment]
@Frosty21 - The jira ticket that's listed there is based on the jira ticket that you have selected via "start work" down in the Issues section of CodeStream. If you want to associate a different jira ticket with the PR, you would need to first click on that ticket in the Issues section and "start work". You'll see that ticket is now highlighted and has an arrow to its left.

Note that we have an enhancement on our roadmap to allow you to select any jira ticket (or even multiple jira tickets) to associate with the PR, rather than limiting you to the currently selected jira ticket.
