### ISSUE TITLE
No code diff visible if commenting on branch the other developer does not have checked out

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#108]
**Describe the bug**
I created a branch. I wrote some code in there and pushed that code.
My colleague then worked on another branch and saw my new comment. When he clicked the comment he was moved to the code position in this ref and not the one I was actually pointing to.
I expected CodeStream to tell him that his codebase is different from and offering him a way to see the code I actually commented on.
I think I saw that before when options like "apply to" were available. I could not reproduce it that way.

**System Info (please complete the following information):**
- Version of the CodeStream extension: 2.1.0+1
- OS + version: Arch Linux
- IDE + version: IntelliJ 2019.2.1

**Log Files**
Sending log files along with your report will help us investigate the issue. Instructions can be found here: https://github.com/TeamCodeStream/CodeStream/wiki/Instructions-for-finding-CodeStream-log-files

**Comment by planteater** [comment]
@xetra11 - Generally speaking, you're right. When there's a diff between the code from the codemark and what the viewer has locally, we should show the Compare and Apply buttons. In this specific case, since your teammate doesn't have the branch, we're not able to do so. We've got a change coming in the next couple of weeks that will allow us to handle this scenario, but in the meantime if your teammate does a git fetch all should be good.

**Comment by planteater** [comment]
Fixed in v5.0.
