### ISSUE TITLE
Jira Server New Ticket fails

### ISSUE THREAD

**Issue by jur-bsw** [TeamCodeStream/codestream#1219]
First:

this is strange, what is normally selectable here:

![image](https://user-images.githubusercontent.com/29754946/195852939-558bb797-c6b4-42ed-98a5-152d4ed4b893.png)

[jiraserver.zip](https://github.com/TeamCodeStream/codestream/files/9786487/jiraserver.zip)

secondly it fails to make a ticket. I think it is also a misconfiguration at server, can u see which?

**Comment by planteater** [comment]
@jur-bsw - That dropdown includes the different issue types from your Jira instances. If it's empty, the issue is likely that all of your issue types have required fields without default values. At the moment, when you create an issue from CodeStream, it only covers the issue title, description and assignee. But if you have additional fields that are required, but don't have a default value, CodeStream isn't able to create an issue of that type.

We do plan to add support for additional fields. Probably early next year. You can follow this issue to get notified:

https://github.com/TeamCodeStream/codestream/issues/528

**Comment by jur-bsw** [comment]
I see thx

**Comment by jur-bsw** [comment]
Great, have a nice weekend

Von: David Hersh ***@***.***>
Gesendet: Freitag, 14. Oktober 2022 15:29
An: TeamCodeStream/codestream ***@***.***>
Cc: Jürgen Scheffler ***@***.***>; Mention ***@***.***>
Betreff: Re: [TeamCodeStream/codestream] Jira Server New Ticket fails (Issue #1219)


@jur-bsw<https://github.com/jur-bsw> - That dropdown includes the different issue types from your Jira instances. If it's empty, the issue is likely that all of your issue types have required fields without default values. At the moment, when you create an issue from CodeStream, it only covers the issue title, description and assignee. But if you have additional fields that are required, but don't have a default value, CodeStream isn't able to create an issue of that type.

We do plan to add support for additional fields. Probably early next year. You can follow this issue to get notified:

#528<https://github.com/TeamCodeStream/codestream/issues/528>
