### ISSUE TITLE
Can't delete comments and comments in files don't show in Pycharm 2019.2.3

### ISSUE THREAD

**Issue by gollum23** [TeamCodeStream/CodeStream#125]
I try codestream, when i try create a comment in a file, the indicator to send comment still in sending state, but comment was sended and i can see in channel, but i can't delete messages, if i return to file the comment don't show.

**Comment by gollum23** [comment]
![Screenshot_20191018_190146](https://user-images.githubusercontent.com/1058783/67134843-dd080b80-f1d9-11e9-819d-e1c8b75fbf0d.png)

**Comment by planteater** [comment]
@gollum23 - Could I trouble you to send a log file? Instructions are below. If you'd prefer, you can send the log file to support@codestream.com rather than posting it here.

1. Go to Help > Debug Log Settings… in your IDE.
2. In the "Custom Debug Log Configuration" dialog, add #com.codestream:trace and then click OK. (Note that you can remove this after you’ve sent us the log files so that logging isn't as verbose.)
3. Restart the IDE.
4. Reproduce the issue and then go to Help > Compress Logs and Show in Finder. This will open the finder where you should see a newly created zip file.

**Comment by gollum23** [comment]
I send you by email. Thanks

**Comment by planteater** [comment]
@gollum23 - Unfortunately, we haven't had any luck so far. The log files you sent don't actually show any errors. Are you still seeing problems? If so, can you try reproducing the problems again and then grab a new log file? Thanks!

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH #125 - Can't delete comments and comments in files don't show in Pycharm 2019.2.3](https://trello.com/c/0gepUBiy/2528-gh-125-cant-delete-comments-and-comments-in-files-dont-show-in-pycharm-201923)

**Comment by marcelofarias** [comment]
@gollum23 We have added additional logging in recent versions to help identify the cause of this issue. Are you still experiencing the same problem? If so, could you send us updated logs once you reproduce it?
