### ISSUE TITLE
Further integration with Github (Organizations)

### ISSUE THREAD

**Issue by see7e** [TeamCodeStream/codestream#1406]
Hello, I'm working with the Code Stream extension in VSCode `version 1.77`, and it speeds up our team's work a lot, but the biggest issue was having to recreate the (existing) Github organization, access to the repositories is impeccable.

I searched about the application's interaction in every way but I didn't find anything in that direction, I also looked here to see if someone had already requested such a feature (I didn't find it, it may have escaped me).

Thank you in advance for your attention and effort to develop this platform!

**Comment by planteater** [comment]
Hi @see7e ! Just to make sure I understand what you're looking for.... I assume we're talking about making it easy for the people in your GitHub organization to get added to your CodeStream organization? The best option we have right now is to make it so that anyone with an email address on your company's domain can join the organization. To set this up, click on your username at the top of CodeStream, then select Organization Admin > Onboarding Settings. Enter your company's email domain there (e.g., "acme.com"), and then anyone that signs up with an acme.com email address will be prompted to join your CodeStream organization.

**Comment by see7e** [comment]
Yes yes! I've seen that, but I was thinking, if GitHub gives the repo's information why it can't provide the organization structure?

If there's some specific teams, the CodeStream application can reach for this info? 

I'm pretty new in thech and don't know much about the API of the GitHub, just looking for cooperate :)

**Comment by planteater** [comment]
Got it! Thanks for the clarification. I'll explore it with the team.
