### ISSUE TITLE
Closed Issue still shows for all new PR/MR

### ISSUE THREAD

**Issue by 1xtr** [TeamCodeStream/codestream#1417]
- CodeStream Extension version: 14.17.0+304
- IDE Version: PhpStorm 2023.1 Build #PS-231.8109.199, built on March 30, 2023
- OS Version: WIn10

Steps to Reproduce:

1. Create any issue and close it

I have one issue in github repo, and it already closed
But it still shows when I create new issue even for gitlab

![image](https://user-images.githubusercontent.com/59780048/230314509-bebb2bb6-d808-42a2-88f8-9d53db885d82.png)

**Comment by planteater** [comment]
@1xtr - The issue that we display as part of the MR creation form is always the most recent issue for which you did a "Start Work" in the Issues section of CodeStream. If you start work on a different issue, that will then be the one that gets shown here.

Note that we do plan to change this model, so that instead of it being tied to Start Work you'll be able to simply select from any of your open issues.

**Comment by 1xtr** [comment]
> @1xtr - The issue that we display as part of the MR creation form is always the most recent issue for which you did a "Start Work" in the Issues section of CodeStream. If you start work on a different issue, that will then be the one that gets shown here.
> 
> Note that we do plan to change this model, so that instead of it being tied to Start Work you'll be able to simply select from any of your open issues.

How I can delete it ?
My issue list is empty

**Comment by planteater** [comment]
At the moment there's really no way to delete it. It just gets replaced the next time you start work on another issue. We recognize that this isn't ideal, and that's part of why we'll be changing the model here.

**Comment by planteater** [comment]
I'll follow up with you once we have the change/fix in place.
