### ISSUE TITLE
 My markings were automatically repositioned to the last line

### ISSUE THREAD

**Issue by SimoesTec** [TeamCodeStream/codestream#182]
I do not work with the CodeStream tab open, when adding a new markup, I identified that all the markings in my codes went to the last line, and now I am unable to reposition them.

Att
Henrique Simões

**Comment by planteater** [comment]
@SimoesTec - Thanks for the report. Could I trouble you to send some log files? Below are instructions for finding them. If you'd prefer not to post them here, you can email them to support@codestream.com. Thanks!

https://docs.codestream.com/userguide/faq/client-logs/

**Comment by planteater** [comment]
Hi @SimoesTec - Just wanted to follow up to see if we could get that log file so that we can address this issue asap. Thanks!

- Go into your VS Code user settings and search for CodeStream.
- Scroll down to the Trace Level setting and make sure it's set to "Debug".
- Reload VS Code and then try to reproduce the issue.
- Open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.
- Change the dropdown select to “CodeStream (Agent)” and grab that output as well.

**Comment by planteater** [comment]
@SimoesTec - I'm going to close this, but I would suggest trying again with a more recent version of CodeStream as we've made a number of changes in this area. If you still see issues, email me at support@codestream.com. Thanks
