### ISSUE TITLE
KIO Client Error

### ISSUE THREAD

**Issue by reznyt** [TeamCodeStream/codestream#184]
When starting PHPStorm, I get a popup which reads:
```
Error - KIO Client
Could not find any application or handler for chrome-extension://cimiefiiaegbelhefglklhhakcgmhkai/_generated_background_page.html
```
The plugin otherwise seems fully functional.

I'm using a fresh install of ArchLinux. I guess I could be missing something? My other ArchLinux machine doesn't have the issue.

**Comment by planteater** [comment]
Hi @laurenblackfox - Thanks for the report! It's possible that this has nothing to do with CodeStream, but our error handling could be picking it up anyway. Could I trouble you for a log file so that we can investigate further? Instructions are below, and feel free to email the file to support@codestream.com if you'd prefer not to post it here. Thanks!

- Go to Help > Debug Log Settings… in your IDE.
- In the "Custom Debug Log Configuration" dialog, add #com.codestream:trace and then click OK. (Note that you can remove this after you’ve sent us the log files so that logging isn't as verbose.)
- Restart the IDE.
- Reproduce the issue and then go to Help > Compress Logs and Show in Finder. This will open the finder where you should see a newly created zip file.

**Comment by laurenblackfox** [comment]
Hi @planteater, thanks for your help! 
[phpstorm-logs-20200508-102855.zip](https://github.com/TeamCodeStream/CodeStream/files/4598177/phpstorm-logs-20200508-102855.zip)

I note that the error seems to persist, even when all other plugins are disabled except CS ...

**Comment by marcelofarias** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [GH #184 - KIO client error](https://trello.com/c/TaasBj9i/3736-gh-184-kio-client-error)

**Comment by marcelofarias** [comment]
Hi @laurenblackfox 

The error doesn't seem related to CodeStream. Based on the logs provided, PhpStorm itself or some other plugin is trying to open the Plasma Integration Chrome plugin. However, KIO (KWin) can't find an application to handle chrome-extension:// URLs.

Is there any any visual indication that indicates that this error is related to CodeStream?

Regards

**Comment by laurenblackfox** [comment]
Yeah, I suspected it'd be something along those lines. The only evidence I have is that the issue ceases as soon as CS is disabled. The issue continues when disabling every single plugin except CS.
In my mind, either CS causing the issue, or it's picking up on something that no other plugin does :)

**Comment by marcelofarias** [comment]
Do you have the `plasma-browser-integration` package installed? Could you try installing it to see if it makes any difference?

**Comment by marcelofarias** [comment]
Also, I see that you're using 7.2.0. Could you try upgrading to 7.2.1 and see if it solves the problem?

**Comment by laurenblackfox** [comment]
plasma-browser-integration is indeed installed, and i've just updated to CS 7.2.1. No effect :(
