### ISSUE TITLE
can't submit review request for large PR

### ISSUE THREAD

**Issue by mikestaub** [TeamCodeStream/codestream#208]
`There are 12,885 total modified lines in this review, which is a lot to digest.`

When I try to submit the review request it doesn't work and I see this in the UI:

`[object Object]`

How can I debug this?

**Comment by planteater** [comment]
@mikestaub - Thanks for the report. Could I trouble you for a log file? Feel free to send it to me directly at support@codestream.com rather than posting it here. Instructions for generating the file are:

- Go into your VS Code user settings and search for CodeStream.
- Scroll down to the Trace Level setting and make sure it's set to "Debug".
- Reload VS Code and then try to reproduce the issue.
- Open the Output view (“View: Toggle Output” from the command palette) and select "CodeStream (Agent)" from the dropdown menu at the top-right. Copy all of the output you see and save it in a text file.

**Comment by planteater** [comment]
@mikestaub - When you tried to submit this code review, were you sharing it to Slack? If so, I think we may have figured out what's going on here.

**Comment by mikestaub** [comment]
Yes I was, I can try to repro and get the logs to you this weekend.

**Comment by planteater** [comment]
@mikestaub - This should be fixed in v8.1.3 of the CodeStream extension, which was just released. Please re-open this though if that proves not to be the case. Thanks
