### ISSUE TITLE
Comments overlap the Extension menus in VSCode 

### ISSUE THREAD

**Issue by hptavakoli** [TeamCodeStream/codestream#226]
After updating VSCode into the last version, comments will overlap the CodeStream menu on the top of the panel, please check this screenshot:

![image](https://user-images.githubusercontent.com/37811925/88835279-54d97c80-d1d5-11ea-9912-83e196d9a3b7.png)

It is the first comment I created on this page, so there is not also any scrolling option to help move it out and use the menu.

**Comment by planteater** [comment]
@hptavakoli - Generally speaking, this is all by design. It just happens that since this comment is associated with the very first line of the file, you aren't able to scroll it away. Since the tops of the global icons are in view though, you should still be able to click on them. If not, change your view to List view via the toggle at the bottom of the page.

**Comment by hptavakoli** [comment]
Yep, I can click on them but it is not easy :)
Thanks, and I think adding a little margin on top or operating these menus on a different row, could solve it forever, up to you, and thanks for your reply.

**Comment by unt1tled** [comment]
> Yep, I can click on them but it is not easy :)
> Thanks, and I think adding a little margin on top or operating these menus on a different row, could solve it forever, up to you, and thanks for your reply.

I agree. I found it weird that the comments always overlaps the header. It would help if there were a margin that would ensure comments don't block the global controls.

**Comment by planteater** [comment]
This has been address by the new UI in 10.0
