### ISSUE TITLE
Login required every time Intellij starts

### ISSUE THREAD

**Issue by voidrot** [TeamCodeStream/codestream#232]
After logging into CodeStream inside of IntelliJ I am always required to login in again if I close/restart IntelliJ. This makes it a hassle to use especially in cases where you need to invalidate the cache and restart the program.

Using Email/Password login. I have not tried with GitHub auth as I don't use GitHub on the project I am using CodeStream on.

**Comment by planteater** [comment]
@voidrot - Could I trouble you to send a log file to support@codestream.com? Close your IDE and then restart, in order to reproduce the issue, then go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file.

Also let me know what OS you're on. Thanks!

**Comment by planteater** [comment]
@voidrot - Just wanted to follow up to see if we could get that log file (as well as OS info). Would love to get to the bottom of this issue for you. Thanks!

**Comment by voidrot** [comment]
@planteater this seems to have been an issue with my install, after reinstalling intelij the issue is not happening any more.
