### ISSUE TITLE
Codemarks: Highlight marked lines

### ISSUE THREAD

**Issue by ghost** [TeamCodeStream/codestream#27]
It would be useful to highlight the background of marked lines using the specified mark color.

**Comment by planteater** [comment]
@nealot - We currently do this just for the new "Trap" codemarks. We were hesitant about doing it across the board for the very same issue you brought up in issue #26. That is, cluttering your source too much.

When someone (either you or a teammate) clicks on the codemark, we take them to the appropriate source file and scroll them to the given block of code. We used to also select the block of code. Would returning to that behavior accomplish what you're looking for? If so, do you think doing it automatically (as we used to) is the best route, or would you prefer some option to "show in file"?

**Comment by nealot** [comment]
@planteater I recently transitioned from using the popular [bookmarks extension](https://github.com/alefragnani/vscode-bookmarks) to codemarks and I'm missing the feature described here: https://github.com/alefragnani/vscode-bookmarks/blob/f986dd2eabf3a7909fcce797e6d7887ba9f504c8/package.json#L212.

My suggestion doesn't really concern the clicking behavior, but rather the inactive state of the lines (i.e. when someone is just scrolling down a file). I would like a setting to color the background of marked lines so that I can quickly glance at the code and associate a selected range with its codemark. I'm not sure if this feature would have any negligible performance or usability implications, so feel free to proceed at your own discretion.
