### ISSUE TITLE
Duplicate Keyboard Shortcuts

### ISSUE THREAD

**Issue by 7ranceaddic7** [TeamCodeStream/codestream#292]
I'm sure this is simply a C:KI (Chair:Keyboard Interface) issue, but I'm stumped.

VSCode Keyboard Shortcuts shows multiple entries with _"similar"_ keychains ...
![image](https://user-images.githubusercontent.com/4062616/95242738-7736da00-07c4-11eb-853d-20790ba1f8d2.png)

I've searched, but cannot find any duplicate copies of CodeStream.
![image](https://user-images.githubusercontent.com/4062616/95243105-fe844d80-07c4-11eb-8401-64ed26bb678b.png)

Could anyone help clue me in?

**Comment by planteater** [comment]
@7ranceaddic7 - The somewhat duplicate entries are actually intentional. For example, we have both of the following to add a new comment:

`Ctrl` + `Shift` + `/`   `C`
`Ctrl` + `Shift` + `/`   `Ctrl` + `Shift` + `C`

We do this just to accommodate people that don't release Ctrl+Shift before hitting `C`.

**Comment by 7ranceaddic7** [comment]
Oh, okay, That makes sense.

Honestly, I thought that was the result of a SxS install of two copies of the extension.
I see them saying the same thing; didn't realize that releasing was an option.  I thought it would break the chain.

Thanks.
