### ISSUE TITLE
Add a forgot password action

### ISSUE THREAD

**Issue by happyharis** [TeamCodeStream/CodeStream#31]
Hi, I am not able to login due to my short term memory of passwords. Thus, I found out that Codestream does not have a forgot password. Please help those people who have short term memory or lost their passwords book. Thanks =)

**Comment by planteater** [comment]
@happyharis - Totally agree, and we do plan to add password-reset functionality in the near future. In the meantime, can you reach out to us at support@codestream.com and we'll get you set up with a new password.

**Comment by nikki-ramirez** [comment]
Just ran into this problem. How timely is support?

We're evaluating CodeStream now (after I saw it in O'Reilly Velocity Conference 2019 in San Jose -- good job, booth team!). I initially set up Slack but our Slack workspace is enormous and it's just unwieldy to use with CodeStream. I signed out and tried to create a new team just in CodeStream but couldn't because I apparently have an account already. I got an email saying I should reset my password. If there was an automated password reset, I wouldn't be staring at my inbox for 10 minutes. 11... 12... :stuck_out_tongue:

**Comment by planteater** [comment]
Password-reset is now available.

**Comment by ahmad-saad** [comment]
Hallo @planteater ,

where ?? I can't find the reset password in IDE or in website

**Comment by planteater** [comment]
@ahmad-saad - It's on the Sign In page in the extension. If you run into any issues, email me at support@codestream.com.

<img width="411" alt="Screen Shot 2020-06-01 at 7 48 59 PM" src="https://user-images.githubusercontent.com/3442587/83465165-06139e80-a441-11ea-9296-806b2be90bc9.png">

**Comment by Moosphan** [comment]
@planteater I found that the forgot password button did not work.

**Comment by planteater** [comment]
@Moosphan - please reach out to us at support@codestream.com and we’ll help you out.
