### ISSUE TITLE
Codemarks: Remove Codemarks from files

### ISSUE THREAD

**Issue by jayakornk** [TeamCodeStream/CodeStream#33]
It would be very great if you added a way to remove Codemarks inside a file.

I just tried to create a Codemarks then share it to Slack then I deleted from the channel. When came back to VSCode, I just couldn't find a way to remove that comment Codemarks.

**Comment by planteater** [comment]
@jayakornk - Thanks for the feedback! In the coming weeks we'll be introducing the ability to "unpin" a codemark so that it no longer appears in the source file (but is still accessible via search of browsing your knowledge base).

In the meantime, you can effectively accomplish the same thing by editing the codemark and selecting the "None" option in the Marker Icon dropdown.
