### ISSUE TITLE
Review BitBucket pull requests

### ISSUE THREAD

**Issue by stefanvuckovic** [TeamCodeStream/codestream#372]
Is there a plan to add support for viewing and reviewing/commenting on PRs from Bitbucket? If yes, can you provide some timeline?

Thanks

**Comment by planteater** [comment]
Absolutely @stefanvuckovic! We're working on GitLab at the moment, and hope to have that ready next month. We'll drive right into Bitbucket from there.

**Comment by anirudhbagri** [comment]
Will this also be working on Bitbucket Server? or this plan is for bitbucket cloud only?

**Comment by planteater** [comment]
@anirudhbagri - Yes, we plan to support both Bitbucket and Bitbucket Server.

**Comment by ElRoberto538** [comment]
+1 For this feature - can't wait!

**Comment by marvin-w** [comment]
Is there any way we can help with this?

From looking around at the source I found that probably https://github.com/TeamCodeStream/codestream/blob/develop/shared/agent/src/providers/bitbucket.ts#L357

would be one thing you'd have to touch. Is there anything else required here?

I've done a similar thing in the past for a sonar plugin and it would probably not be that much different (apart from being in typescript) - https://github.com/mc1arke/sonarqube-community-branch-plugin/pull/185

How would I connect my local node server (from https://github.com/TeamCodeStream/codestream/blob/develop/jb/docs/dev.md) with the IntelliJ plugin?

**Comment by ppezaris** [comment]
Hi @marvin-w thanks for the offer! very much appreciated :)

our goal with our PR integrations is to offer a very rich user experience in the editor, as you can see with our github PR and soon gitlab MR integrations. to get a sneak peek of gitlab, and get an idea of the scope of work involved, have a look at https://github.com/TeamCodeStream/codestream/pull/443 which is a WIP but fairly close to done. at current count, it's an 11K line diff (!) here's a quick walkthrough of the features: https://youtu.be/SPepHfaQK10

to do a very basic form of integration wouldn't be as heavy of a lift, but that hasn't been our strategy -- we aim pretty high with these important integrations.

having said that, bitbucket won't be as much work as github nor gitlab because their PRs are simple by comparison. So perhaps 7K lines of code?

once we're ready to start on bitbucket, if you're interested, we'd be happy to include you in that project.

we don't yet have an open slack channel (we don't use discord), but send me an email at pez@codestream.com and we'll include you as soon as we're ready, and can also offer some guidance to get you set up with local development of codestream in jetbrains editors.

**Comment by marvin-w** [comment]
Thanks for the followup @ppezaris.

I sent you an email. Your plans sound great and I'd happy to support you when you start with this feature.

Do you also intend to integrate the "Code Insights" section of Bitbucket? That, for me would be really nice feature.

Example use case: Sonarqube publishing a report to Bitbucket and you can simply click through the code smells in your IDE.

**Comment by theofred** [comment]
@planteater I just found CodeStream and this integration for VS Code. Reviewing Bitbucket PRs would be the changing feature for my team to move to CodeStream.
Is there any update on how far away this feature is? Thank you very much!

**Comment by planteater** [comment]
@theofred - I think we're still at least three or four months away.

**Comment by finn-wa** [comment]
Any updates? The Bitbucket Cloud PR UI is killing me 😂

**Comment by gpinkham** [comment]
Glad I noticed this.  I assumed something was broken in VS Code.  it was why I installed the plugin in the first place.    I'll remove and track this issue and try code stream again when this feature happens.

**Comment by f-tischler** [comment]
@ppezaris any updates?

**Comment by Aleksnako** [comment]
@ppezaris any updates?

**Comment by sadikkahveci** [comment]
Hello, in documents; I can see tthe interagtion of Bitbucket server but 
I cound't find in my Visual Studio Pull request section. 
Did I miss somehing ?

**Comment by planteater** [comment]
@sadikkahveci - For Bitbucket you can create PRs from CodeStream, but you currently can't review them. Right now Bitbucket support is targeted for later this year.

**Comment by leonidr** [comment]
@planteater - I've seen your comment in #1291 that you plan to release it in EOF January / February.
Do you have an updated estimation?

**Comment by planteater** [comment]
Sorry for the delay on this @leonidr - Probably have another four weeks or so to go to wrap this up.
