### ISSUE TITLE
Question: How to get the warning for "Conflict Merge"?

### ISSUE THREAD

**Issue by rafael-trevisan** [TeamCodeStream/CodeStream#41]
Hi all,

I am using CodeStream on VSCode and I am quite happy with it. It's a quite impressive extension!

I've seen a video showing a warning when apparently two users change the same file, something like to prevent "conflict merge". I did some tests here with some co-workers but we didn't get such a warning. Is there any need for any specific setting or condition to get those warnings? We're using CodeStream with Slack.

Another question (maybe should be a different topic though) is about the right side panel. When I click on the CodeStream icon on the menu bar, it hides my "Left Panel" and shows the CodeStream in a 50%-50% panel in the VSCode. I was wondering if there is a way to always show the CodeStream panel in a pre-fixed size so I don't need to resize (dragging it) every time I open it.

Also about panels, when I have CodeStream panel opened if I click on any file to view or work ok, VSCode opens it in the "right side panel" (where CodeStream is) instead of in the main and centred panel. Is there any way to force VSCode to open files always in the centre panel?

Thanks in advance!

**Comment by planteater** [comment]
The merge-conflict banner was part of our very early extension for Atom, but we had some paradigm changes since then that caused them to be eliminated. We definitely intend to bring them back though.

As for our activity bar entry causing the sidebar to close, unfortunately don't have a lot of control here. At the moment, CodeStream doesn't have a view in the sidebar so when we open the CodeStream pane we close the sidebar rather than switching you to a different sidebar entry. As an alternative, if you click on the CodeStream entry in the VS Code status bar, that will toggle the CodeStream pane without impacting your sidebar.

Lastly, the issue with files being opened in the CodeStream pane, another issue where we don't have as much control as we'd like. Supposedly VS Code will be introducing some type of pinning functionality that might give us more control over the pane, and prevent other tabs from being opened in it.

**Comment by planteater** [comment]
@rafael-trevisan - These warnings were brought back as part of our 7.0 release.

https://www.codestream.com/blog/codestream-7-0-code-reviews-in-your-ide-and-live-view

**Comment by rafael-trevisan** [comment]
That's great! I've checked the feature and it looks amazing!
