### ISSUE TITLE
On-prem broadcaster issue

### ISSUE THREAD

**Issue by pepijnve** [TeamCodeStream/codestream#426]
A couple of days ago we started noticing some issues with client updates. One person would add a comment and other people would not see those until they restarted their IDE. I had not updated our on-prem server for some time so I suspected this may be an incompatibility between the most recent IDE plugin and the older server. After upgrading the server everything worked correctly again.

What would be great here is if the client UI would notify you about this. At the moment there's no way to know the on-prem server needs an update and I'm a bit reluctant to do this automatically as part of a cron job (unless that's considered the best practice of course).

**Comment by planteater** [comment]
Hi @pepijnve - We normally do an email blast for all but very minor updates, and the client does have messaging for required updates. But I suspect that the update may have been a red herring because I can't think of any backend updates we've done in the last couple of months that would have been related to the broadcaster. The type of issue you describe is typically a broadcaster issue.

Let me discuss with the team to see if there's anything else we should do at the moment to make sure everything is truly working. Do you happen to recall which version of the backend you were running prior to this update? Thanks!

**Comment by pepijnve** [comment]
> But I suspect that the update may have been a red herring

Could be indeed. It might just be the restart of all the containers that fixed it.

> Do you happen to recall which version of the backend you were running prior to this update?

I'm afraid I didn't make notes of that. The previous update was right after you informed me that Jira API key support had been added. And the update that 'fixed' things was around 3/3/2021 17:00 CET.

**Comment by jimmyjayp** [comment]
Hi Pepijnve, this is certainly symptomatic of a broadcaster connectivity problem which would mean restarts of the server-side services as well as the clients might make it go away and appear transient.  To better diagnose, we'd want to capture logs (ideally both on the client and server) while this is going on.

To collect logs on the server, you'd run '~/.codestream/codestream --logs 3h' (for example) which would capture the past 3 hours of logs in a tarball which you could email to us.  Capturing client logs is described in our user guide here https://docs.codestream.com/userguide/faq/client-logs/ .

**Comment by pepijnve** [comment]
Ok, things are working fine at the moment. If the problem reoccurs I'll collect the logs and send them over.

**Comment by planteater** [comment]
Sounds good. I'll close this for now, but we'll re-open as needed.
