### ISSUE TITLE
publish to Open VSX

### ISSUE THREAD

**Issue by akosyakov** [TeamCodeStream/codestream#430]
We are running Web version of Code in Gitpod: www.gitpod.io. You can enable it in settings: https://www.gitpod.io/docs/feature-preview/#default-ide

This version is not allowed to use MS VS Code extensions Marketplace, since it is not MS product. So we connect to Open VSX instead: https://open-vsx.org/ It is a vendor neutral alternative.

Our users want to install CodeStream extension but fail since it is not published to Open VSX: https://community.gitpod.io/t/install-extensions-from-url/2904

Please publish it as well there 🙏  Docs are here: https://github.com/eclipse/openvsx/wiki/Publishing-Extensions Technically it should be straightforward.

**Comment by planteater** [comment]
Thanks for reaching out on this @akosyakov! This is definitely on our radar, although I don't have a specific timetable just yet. Since there's already an open issue for this, I'm going to close this one. Could I trouble you to follow the one below?

https://github.com/TeamCodeStream/codestream/issues/415
