### ISSUE TITLE
Reviews beeing created on branch switch

### ISSUE THREAD

**Issue by agenda-web** [TeamCodeStream/codestream#444]
**Version**
CodeStream 10.7.0 on VSCode

**Description**
CodeStream suddenly started to create reviews on an unrelated merge whenever I switch branches. It does not matter to which branch i switch and it happens every time. The review assigns to myself and implies I've made changes, wether I made any or not.

**Comment by marcelofarias** [comment]
Hi @agenda-web, thanks for the feedback!

If you simply dismiss the notification, no review will be created. In case you don't want to be prompted at all, you can disable it under Notification Settings.

We are currently working on better identification of code authorship and improving the triggering mechanism so it won't prompt you when you are simply switching branches rather than actually pulling new commits into the current branch.

**Comment by agenda-web** [comment]
Hi @marcelofarias, thank you for the quick response.

You're absolutely right, I must have always subconciously clicked on review on every notification instead of simply dismissing them.

Thanks for your help, I'm looking forward to further improvements to this already great app.
