### ISSUE TITLE
Server response unstable

### ISSUE THREAD

**Issue by wanlinruo** [TeamCodeStream/codestream#455]
At present, the company has set up the private server, but found a problem, sometimes the message response is slow, the receiver can not see the message in time, have to restart the Android Studio to see it, is there any way to troubleshoot?
![image](https://user-images.githubusercontent.com/21278600/112289373-39bdfe80-8cc9-11eb-91e4-246cddc97743.png)
Plug-in version: 10.7.1+140
API-Server version: 8.2.26
The broadcaster version: 8.2.24
Onprem-admin version: 8.2.0

**Comment by planteater** [comment]
@wanlinruo - I should add that if you'd prefer not to share the log files here, please send them to support@codestream.com and just reference GitHub issue #455 in the email subject.

**Comment by jimmyjayp** [comment]
We do use websockets for the broadcaster, but we don't use nginx.  The broadcaster is a nodejs socket cluster app. It accepts websocket connections directly.  Your problem is likely due to a connectivity problem between your computer and your on-prem server.  You can test connectivity from your workstation, by opening a web browser on the same machine as your IDE and going to http://<codestream-onprem-server>:12080/no-auth/status (assuming you're running the broadcaster on port 12080).  If things are configured and working properly, you should get an 'OK' in the browser window.

**Comment by wanlinruo** [comment]
What I need to inform is that our service is deployed in the local computer room, so Nginx is not used as a proxy. Secondly, except for the untimely message synchronization, other services are normal, which means that the machine and the service are in a connected state. Visit http://server-url:12004/no-auth/status(the broadcaster on port 12004), it is normal, return ok. The detailed description of the current problem is that colleague A initiated a review request in Android studio to colleague B, but colleague B could not receive the request in time in Android studio, and there is no refresh button in the Android studio plugin, unless the Android studio is reopened to see this If it is requested, it will be reviewed. I think this is too inefficient. I would like to ask if it is a configuration problem?

**Comment by jimmyjayp** [comment]
When requests aren't seen in real-time it's usually an indication of a connection problem between the client (IDE) and the broadcaster.  As for the proxy, I'm not really certain what your concerns are.  It might help to think of the CodeStream server as a big box that, today, has 3 public-facing ports; one for the api (IDE extension), one for broadcaster (IDE extension) and one for the admin server (browser). Internally it uses other connections between services, including mongodb & rabbitmq but clients don't see them. We do plan to add a proxy to the collection of services so that there's only one public-facing port for everything in the future, but we don't have that today.  If you're running our docker-ized On-Prem installation, you should not worry about the internals of how the server-side services work.  You certainly can, but that will require a significantly deeper understanding of the internals which really isn't relevant to using it. Plus, you won't be able to make changes on the internals anyway unless you plan to do development on the services themselves.

Every client (person running the CodeStream extension) should be able to connect to the CodeStream server on both the API & broadcaster ports.  The /no-auth/status URL can be used on both services (api & broadcaster) to test connectivity between the server and client.  If it works in a client's web browser, it _should_ work in their IDE.  If it doesn't, we'd need to see the logs for the IDE client whose having problems. The link for gathering logs is posted above in my earlier reply.

**Comment by wanlinruo** [comment]
When I restarted the service, the notification problem was significantly improved, but I recommend adding a refresh button to the client plugin that can be used to manually refresh messages @jimmyjayp @planteater

**Comment by jimmyjayp** [comment]
If connectivity is working properly, you should not need to refresh.  I'm glad things are improved.  If you continue to see problems, I advise looking at the agent logs (or sending them to us).
