### ISSUE TITLE
Specify which remote to use out of multiple remotes

### ISSUE THREAD

**Issue by shoaibshakeel381** [TeamCodeStream/CodeStream#48]
hey, is it possible to specify which remote should CodeStream use , if we have more than one remotes configured?

**Comment by planteater** [comment]
@shoaibshakeel381 - When you create a codemark, CodeStream actually leverages all of the remotes associated with the block of code. Say, for example, you and a teammate are both working in the same repo, but you have remotes A and B configured, and she has remotes B and C. When you create a codemark with code from that repo, your teammate will see the code associated with the correct file because the commonality of remote B lets us know that we're dealing with the same repo.
