### ISSUE TITLE
"Request codestream/provider/generic failed with message: Not Found: 404 Project Not Found" for GitLab MRs

### ISSUE THREAD

**Issue by eblanshey** [TeamCodeStream/codestream#495]
This error is showing after setting up an MR integration with GitLab. No MRs are being displayed in the panel as a result. I CAN use the "Load MR from URL" feature and the MR loads successfully. It's the MR list that doesn't work.

> Request codestream/provider/generic failed with message: Not Found: 404 Project Not Found

It's not clear which project it's looking for, as it never asked me that.

**Comment by planteater** [comment]
Thanks for the report @eblanshey! We'll get on this asap.

**Comment by eblanshey** [comment]
Looks like this may be an issue concerning which project it's trying to load. Even though direct MR links open, when I make comments on code in an MR review, it links the file to the wrong project. Probably there should be a configuration or dropdown somewhere to select which project's MRs should be used.

**Comment by planteater** [comment]
@eblanshey - Could I trouble you to run the following curl command? Insert your toke in for the XXX.

curl https://gitlab.jaumo.com/api/v4/projects/294 -H "PRIVATE-TOKEN: XXX"

We're particularly looking for what the "path_with_namespace" field is in the returned data. Thanks!

**Comment by cstryker** [comment]
@eblanshey Not sure if you saw @planteater 's comment above about running a curl command (I realized it was wrong for your situation so I asked him to delete it, but I still see it for some reason). In any case, we're a bit stumped by this issue over here. If you wouldn't mind helping us out, could you:

(1) create a Personal Access Token in GitLab (I'll assume you know how to do this, if not I can let you know)

(2) copy the PAT, get the project ID of the project you are having problems with (again, I can guide you if you need), and then run this curl command from a terminal:

curl https://gitlab.com/api/v4/projects/<projectID> -H "Authorization: Bearer <your_PAT>"

or if that doesn't work, you can try:

curl https://gitlab.com/api/v4/projects/<projectID> -H "PRIVATE-TOKEN: <your_PAT>"

(3) assuming you get good JSON data back from one of those API calls, get the "path_with_namespace" field from the returned JSON data, then run encodeURIComponent() on the value of that field (in particular, you'll need to replace '/' characters with '%2F', the run the following curl command:

curl https://gitlab.com/api/v4/projects/<encoded_path_with_namespace> -H "Authorization: Bearer <your_PAT>

(or the PRIVATE-TOKEN header if that doesn't work).

If you get a 404 response to that call, that's what we're running into within CodeStream as well, and we might have to escalate that to a support ticket with GitLab, since that is supposed to work. But if that call works, we might have to do some more head-scratching.

Appreciate your patience and assistance on this.

**Comment by planteater** [comment]
@eblanshey - Just wanted to follow up to see if there was any chance we could get the results of those curl commands. Thanks!

**Comment by eblanshey** [comment]
Hy @planteater it's been a busy week but I keep in mind to do it when I can! Sorry for the wait.

**Comment by bcanzanella** [comment]
@eblanshey another CS user ran into a very similar issue recently and it was related to a configuration server-side in their apache instance that was un-encoding the slash in <encoded_path_with_namespace>. This link describes the issue & the fix (https://stackoverflow.com/questions/63073924/gitlab-api-v4-returns-404-on-project-search-when-using-namespace-projectname-ins) but I'll paraphrase here what they said to us:

>Looking at gitlab logs, we're seeing the slash show up in the logs (project/repo). If we change it to AllowEncodedSlashes NoDecode, then the slash is being re-encoded (project%252Frepo). And if we change the ProxyPass line to nocanon, then it ends up as project%2Frepo, and works correctly.

**Comment by planteater** [comment]
@eblanshey - I'm going to go ahead and close this out, but if adjusting those settings doesn't solve the issue for you please feel free to re-open, or reach out to me directly at support@codestream.com. Thanks!
