### ISSUE TITLE
(VS Code) Login failed: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by ohlookitsderpy** [TeamCodeStream/CodeStream#55]
```
Request initialize failed with message: Login failed:
Cannot read property 'id' of undefined
```

Due to this error, I cannot login. 
(VS Code Info: Insiders, latest.)

I also get a weird bug where it keeps refreshing the verify email page, but I don't know if this is related or not. <img src='https://u.derpyenterprises.org/7c2007.gif'>
(Browser Info: Firefox Developer Edition, latest.)

**Comment by planteater** [comment]
@ohlookitsderpy - Sorry about the problems! The issue here is that little redirect loop you're in is preventing you from getting to the next step in the signup process where you enter a team name. Since you're not yet on a team, that's why you get the error when you try to login in the extension.

Let's try a couple of things. First, a hard refresh in your browser. See if that takes you to the next step. If not, try going to the following URL and starting the signup process over again. Maybe in a private window for good measure.

https://app.codestream.com/signup?force_auth=true

Let me know if either of those get you to the next step, where you enter a team name.

**Comment by ohlookitsderpy** [comment]
Doing a hard refresh returns this: 
<img src='https://u.derpyenterprises.org/dbde69.png'>

Signing up again using the URL you provided returns this: <img src='https://u.derpyenterprises.org/47fff3.png'>

**Comment by planteater** [comment]
OK, let's try one last thing. Try hitting this URL:

https://app.codestream.com/signin

If that doesn't work, just let me know the team name you'd like use and we'll just take care of it on the backend for you. :-)

**Comment by ohlookitsderpy** [comment]
I managed to login using that URL and set a team name. I also managed to login on VS Code. Thanks! :)
