### ISSUE TITLE
vscode CodeStreamApiProvider.getTelemetryKey FAILED

### ISSUE THREAD

**Issue by zenchan** [TeamCodeStream/codestream#564]
vscode plugin cannot connect to csbcast

[(node69245) [DEP0005] DeprecationWarnin.log](https://github.com/TeamCodeStream/codestream/files/6458994/node.69245.DEP0005.DeprecationWarnin.log)

**Comment by jimmyjayp** [comment]
Can you please clarify if you're running the codestream-server services in development (as opposed to our CodeStream On-Prem product which uses docker)?

**Comment by zenchan** [comment]
mkdir ~/.codestream
cd ~/.codestream
curl -s -O https://raw.githubusercontent.com/TeamCodeStream/onprem-install/master/install-scripts/codestream
chmod +x codestream
~/.codestream/codestream --quickstart

I used this way to deploy codestream-server, but it ran with development not onprem.

**Comment by jimmyjayp** [comment]
So on closer inspection of your client log, it appears you aren't able to connect to the API server either. Are you able to login to codestream?

If possible, please let me know what your codestream URL looks like.  Thx.

**Comment by jimmyjayp** [comment]
I may also ask you for your server logs if that's not too much trouble.  Instructions here https://docs.codestream.com/onprem/configs/single-host-linux/#capture-server-logs

**Comment by zenchan** [comment]
> I may also ask you for your server logs if that's not too much trouble. Instructions here https://docs.codestream.com/onprem/configs/single-host-linux/#capture-server-logs
@jimmyjayp 

https://github.com/TeamCodeStream/codestream-server#readme
I used this way to deploy codestream-server. These are the server log:
[api-20210513.log](https://github.com/TeamCodeStream/codestream/files/6471910/api-20210513.log)
[broadcaster-20210513.log](https://github.com/TeamCodeStream/codestream/files/6471911/broadcaster-20210513.log)
[opadm-20210513.log](https://github.com/TeamCodeStream/codestream/files/6471912/opadm-20210513.log)

I used the vscode plugin, and it cannot connected to broadcaster server.
[vscode-plugin.log](https://github.com/TeamCodeStream/codestream/files/6471933/vscode-plugin.log)

**Comment by cstryker** [comment]
@zenchan after looking at your logs it appears that something went wrong with your onprem codestream installation, resulting in a faulty configuration. Unfortunately there is no way to know exactly what went wrong so I think we're just going to have you start all over again. The installation procedure is a bit different than the first time you went through it because since your last install we have had to make some changes. We have removed installation of a mongo database from our installation; it now has to be downloaded and run separately. But the updated instructions should be pretty clear on how to do this.

First, we'll need you to remove the codestream containers you previously downloaded. If you have no other docker volumes other than what you downloaded for codestream, this will be pretty straightforward. If this is the case, run:

./codestream --reset
docker volume rm $(docker volume ls | awk '{print $2}' |grep -v VOL)
rm -rf ~/.codestream

This will stop your containers, REMOVE ALL DOCKER VOLUMES FROM YOUR SYSTEM, and remove the initial control script you downloaded to start the installation. Again, this will REMOVE ALL DOCKER VOLUMES FROM YOUR SYSTEM. Don't do this if you have other docker volumes not related to CodeStream; we'll have to guide you through a separate process if that's the case.

Assuming you can do this and it's successful, you'll want to run through the installation again per https://docs.codestream.com/onprem/. But PLEASE NOTE: This guide has changed since the last time you used it, you'll want to make sure you're not looking at a cached version of the guide in your browser. You'll know you're looking at the correct version of the guide if you see this as the second line item in the instructions:

2. CodeStream has a dependency on MongoDB (v4.2.11) and it is required that you bring your own instance.

Note, then, that the correct instructions require you to download and run a mongo docker container separately from the codestream docker install. This should be straightforward and an easy recommendation is described in the guide.

To ensure we can diagnose any problems that occur during the installation, please capture all the output of the codestream control script when you are running the quick start. If you run into problems later, that output could be helpful in diagnosing the problem.

Hopefully, whatever happened the first time won't happen this time, and all will be well. But if not, we will need to look at your complete log set across all the backend services. You can capture all these logs in a single command: "~/.codestream/codestream --logs 24h" which will put the logs for the past 24 hours into a tar file. Then send that tar file to us. 

Sorry for the long-winded comment. Hopefully it's worth your time and effort.

**Comment by zenchan** [comment]
@cstryker the problem was done. Thank you.
