### ISSUE TITLE
GitHub integration requires full permissions to private repos while the "security page" on your webpage clearly states otherwise

### ISSUE THREAD

**Issue by gesof** [TeamCodeStream/codestream#571]
https://www.codestream.com/security

> Access to your Source Tree
CodeStream servers do not require access to your source code. To establish links between discussion threads and blocks of code, we use commit IDs and line number offsets, which are captured by the IDE when the thread is created.

However, the following permissions are actually requested:

> ### Permissions
> Access notifications
 Read all user profile data
 **_Full control of private repositories_**
 Access user email addresses (read-only)

Are really needed such permissions so one can fully delete our private repos ?

**Comment by planteater** [comment]
Hi @gesof - Thanks for reaching out on this. The copy from our security page refers to the fact that CodeStream's core code discussion/code review functionality doesn't need any special access to your source tree. When you discuss code we simply leverage your IDE's access to the code to make that happen.

The GitHub integration is a separate issue. That integration allows you to create, manage and review PRs from within CodeStream. In order to provide that functionality we need to be able to read and write to your GitHub organization. Unfortunately GitHub doesn't provide granular scopes so that access you depicted in your screenshot is what's required.
