### ISSUE TITLE
Codestream is not loading gitlab issues

### ISSUE THREAD

**Issue by jesus-medina** [TeamCodeStream/codestream#587]
I'm using Codestream on Android Studio and Gitlab issues are not loaded. Could you confirm if this feature is available to private repositories?

**Comment by planteater** [comment]
@jesus-medina - The integration should work just fine with private repos. One possible issue would be if the repo were configured such that you needed to enter a password in order to fetch. Assuming that isn't the case, we'll probably need a log file in order to dig into this more.

Reproduce the issue and then in your IDE go to Help > Collect Logs and Diagnostic Data. This will open the finder where you should see a newly created zip file. If you'd prefer not to post it here, feel free to send it to me at support@codestream.com. Thanks!

**Comment by planteater** [comment]
Hi @jesus-medina - Just wanted to follow up on my previous reply. Thanks!

**Comment by planteater** [comment]
@jesus-medina - I'm going to close this issue out for now, but when you are able to grab that log file please send it to me at support@codestream.com and we'll get this figured out for you. Thanks
