### ISSUE TITLE
Is there any idea work with gitee

### ISSUE THREAD

**Issue by typinging** [TeamCodeStream/codestream#691]
we use https://gitee.com/ to manage our code repository
can we work with gitee when use codestream

**Comment by planteater** [comment]
@typinging - You can use CodeStream's core features for discussing code (Codemarks) and reviewing work-in-progress code (Feedback Requests), because they only require that the repo be managed by git, but we don't have an integration with gitee. So you want get support for pull requests or anything like that.

**Comment by typinging** [comment]
ok, thanks
