### ISSUE TITLE
Can't associate OpenTelemetry services to the repository

### ISSUE THREAD

**Issue by leocavalcante** [TeamCodeStream/codestream#750]
My OpenTelemetry service doesn't shows up on the Select entity box at Observability tab.

**Comment by planteater** [comment]
@leocavalcante - Apologies for the confusion, but this integration is tied to the Errors Inbox, and that isn't yet available for Open Telemetry. It's definitely on the roadmap though, and hopefully coming soon. For now though, it's only available for APM.

**Comment by peron** [comment]
We're going to focus on performance enhancements next year in the company, and I thought CodeStream would fit perfectly for that task. However, I ran into the same issue as the OP. We have all of our services instrumented with OpenTelemetry and non of them showed up. Even two years down the line it hasn't been implemented!

Is there any update regarding this? Can you share any link to where we can follow the progress of it?
Since OpenTelemetry seems to be advancing rather quickly now, even with New Relic as a major contributor, I hope that this feature isn't far away!

**Comment by planteater** [comment]
@peron - We'll have some OTel support coming in mid January. Golden metrics, SLOs and related services will be part of this initial support. We're still looking into whether or not OTel will be able to support features like anomaly detection/code-level metrics.
