### ISSUE TITLE
Clicking Slack notification should open CodeStream panel

### ISSUE THREAD

**Issue by joelwatson** [TeamCodeStream/CodeStream#8]
The Slack notifications are clickable, but they don't do anything when you click them. I think they should open the CS panel...probably make this configurable?

CS Extension Version: 0.15.0
VS Code Version: 1.28.0

**Comment by eamodio** [comment]
Unfortunately we are blocked by the current vscode apis (see https://github.com/Microsoft/vscode/issues/51013 and https://github.com/Microsoft/vscode/issues/46571). 

Because of those api limitations that left us with 2 options with regards to the notifications.

1. Put buttons on the notification to "Open" the message, BUT the notification will NOT go away unless you click the "Open" button or explicitly close the notification
1. Don't have any buttons and the notification will go away after a short timeout, BUT you can't interact with them

Neither of these options are ideal, but we opted for 2 to be less invasive.

It does looks like there will be movement on either https://github.com/Microsoft/vscode/issues/51013 or https://github.com/Microsoft/vscode/issues/46571 very soon, so once they land we can have a much better experience.

Although if we provided an option to switch between 1 & 2 above, would you want that?

**Comment by joelwatson** [comment]
Hmm...I definitely wouldn't want to have to manually dismiss things, so happy with any functionality that doesn't require that :)

**Comment by planteater** [comment]
This was fixed with v0.18, if you're running the Insider's edition of VS Code. Otherwise, you'll see it with the next official release of VSC.

**Comment by eamodio** [comment]
Fixed in v0.24, but you must be using vscode 1.29 to see the update.
