### ISSUE TITLE
[Question] If moving from one Slack server to another will CodeStream migrate codemarks?

### ISSUE THREAD

**Issue by xetra11** [TeamCodeStream/CodeStream#98]
We are about to move to another slack server soon and are connected to another currently. How will the codemarks of our repo behave when migrating to the other server?

**Comment by planteater** [comment]
When you move to the new workspace will you be importing the channels from your existing workspace or starting from scratch?

**Comment by xetra11** [comment]
From Scratch

**Comment by planteater** [comment]
This will likely change in the next month or two, but at the moment if your team is connect to Slack, replies to a codemark are stored exclusively on Slack. Specifically, once a codemark is created, the messaging around it goes directly from your IDE to the Slack backend.

When you change your Slack workspace we'll be able to easily migrate your codemarks, but if you want the replies to those codemarks to be preserved as well you'll need to export any channels in which you shared codemarks and then import them into your new workspace. Since you already know that you'll be changing Slack workspaces, you might want to try to minimize the migration process by sharing all of your codemarks into a single channel in your current workspace.

When the time comes, just reach out to support@codestream.com and we'll take care of this for you.
